name: "构建Docker镜像-python-nodejs"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像-python-nodejs
    steps:
      - name: docker build and push
        run: |
          git clone https://github.com/ronghuaxueleng/mitmproxy.git mitmproxy
          cd mitmproxy
          NODE_VERSION=22.17.1
          CHECKSUM="70c448f3361f5beb6627ab2a5750c2005f44007a13e2faa8a72ddd61605db9a6"
          docker build -t ronghuaxueleng/python-nodejs . --build-arg CHECKSUM=$CHECKSUM --build-arg NODE_VERSION=$NODE_VERSION -f DockerfilePythonNode
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ronghuaxueleng/python-nodejs
