name: "构建Docker镜像"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像
    steps:
      - name: docker build and push
        run: |
          git clone https://github.com/ronghuaxueleng/mitmproxy.git mitmproxy
          cd mitmproxy
          VERSION=7.0.4
          wget https://snapshots.mitmproxy.org/$VERSION/mitmproxy-$VERSION-py3-none-any.whl
          docker build -t ronghuaxueleng/mitmproxy . --build-arg MITMPROXY_WHEEL=mitmproxy-$VERSION-py3-none-any.whl
          docker build -t ronghuaxueleng/mitmproxy:$VERSION . --build-arg MITMPROXY_WHEEL=mitmproxy-$VERSION-py3-none-any.whl
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ronghuaxueleng/mitmproxy
          docker push ronghuaxueleng/mitmproxy:$VERSION
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1