name: "构建Docker镜像-with-nodejs"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像-with-nodejs
    steps:
      - name: docker build and push
        run: |
          git clone https://github.com/ronghuaxueleng/mitmproxy.git mitmproxy
          cd mitmproxy
          VERSION=6.0.2
          NODE_VERSION=17.0.1
          wget https://snapshots.mitmproxy.org/$VERSION/mitmproxy-$VERSION-py3-none-any.whl
          docker build -t ronghuaxueleng/mitmproxy-nodejs -f DockerfileWithNodeJs .
          docker build -t ronghuaxueleng/mitmproxy-nodejs:$VERSION-$NODE_VERSION -f DockerfileWithNodeJs .
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ronghuaxueleng/mitmproxy-nodejs
          docker push ronghuaxueleng/mitmproxy-nodejs:$VERSION-$NODE_VERSION