name: "构建Docker镜像"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像
    steps:
      - name: docker build and push
        run: |
          VERSION=7.0.2
          docker build -t ronghuaxueleng/mitmproxy . --build-arg MITMPROXY_WHEEL=mitmproxy-$VERSION-py3-none-any.whl
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ronghuaxueleng/mitmproxy