name: "构建Docker镜像-with-nodejs"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Docker镜像-with-nodejs
    steps:
      - name: docker build and push
        run: |
          git clone https://github.com/ronghuaxueleng/mitmproxy.git mitmproxy
          cd mitmproxy
          VERSION=6.0.2
          NODE_VERSION=14.18.1
          CHECKSUM="8d6d2b71b76dc31bbcf12827b9e60212bc04a556c3498e75708d38f5eb4ae6eb"
          wget https://snapshots.mitmproxy.org/$VERSION/mitmproxy-$VERSION-py3-none-any.whl
          docker build -t ronghuaxueleng/mitmproxy-nodejs . --build-arg CHECKSUM=$CHECKSUM --build-arg VERSION=$VERSION --build-arg NODE_VERSION=$NODE_VERSION -f DockerfileWithNodeJs
          docker build -t ronghuaxueleng/mitmproxy-nodejs:$VERSION-$NODE_VERSION . --build-arg CHECKSUM=$CHECKSUM --build-arg VERSION=$VERSION --build-arg NODE_VERSION=$NODE_VERSION -f DockerfileWithNodeJs
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ronghuaxueleng/mitmproxy-nodejs
          docker push ronghuaxueleng/mitmproxy-nodejs:$VERSION-$NODE_VERSION
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1